### ISSUE TITLE
Error writing received data via HEC: java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by wushujames** [damiendallimore/SplunkModularInputsJavaFramework#21]
I'm using the "Monitoring of Java Virtual Machines with JMX" app (https://splunkbase.splunk.com/app/668/ ). I am running it in batch mode. I am getting a java.util.ConcurrentModificationException error when sending. Stack trace is as follows:

```
02-04-2016 13:04:56.747 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/SPLUNK4JMX/bin/jmx.py" Error writing received data via HEC: java.util.ConcurrentModificationException
02-04-2016 13:04:56.747 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/SPLUNK4JMX/bin/jmx.py"    at java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:966)
02-04-2016 13:04:56.747 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/SPLUNK4JMX/bin/jmx.py"    at java.util.LinkedList$ListItr.next(LinkedList.java:888)
02-04-2016 13:04:56.747 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/SPLUNK4JMX/bin/jmx.py"    at com.splunk.modinput.transport.HECTransport.rollOutBatchBuffer(Unknown Source)
02-04-2016 13:04:56.747 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/SPLUNK4JMX/bin/jmx.py"    at com.splunk.modinput.transport.HECTransport.createAndSendHECEvent(Unknown Source)
02-04-2016 13:04:56.747 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/SPLUNK4JMX/bin/jmx.py"    at com.splunk.modinput.transport.HECTransport.transport(Unknown Source)
02-04-2016 13:04:56.747 -0800 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/SPLUNK4JMX/bin/jmx.py"    at com.splunk.modinput.jmx.JMXModularInput$ProcessServerThread.run(Unknown Source)
```

From looking at your code at https://github.com/damiendallimore/SplunkModularInputsJavaFramework/blob/master/src/com/splunk/modinput/transport/HECTransport.java#L255, it appears that you are not synchronizing on the batchBuffer when you are iterating over it.

```
		for (String event : batchBuffer) {
			sb.append(event);
		}
```

According to https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedList(java.util.List), you need to synchronize it manually when iterating.

```
It is imperative that the user manually synchronize on the returned list when iterating over it:

  List list = Collections.synchronizedList(new ArrayList());
      ...
  synchronized (list) {
      Iterator i = list.iterator(); // Must be in synchronized block
      while (i.hasNext())
          foo(i.next());
  }
 
Failure to follow this advice may result in non-deterministic behavior.
```

**Comment by damiendallimore** [comment]
Good spotting. I'll fix the code ASAP.
