### ISSUE TITLE
Error getting password from encrypted store

### ISSUE THREAD

**Issue by sodle** [damiendallimore/SplunkModularInputsJavaFramework#24]
I get the following error in splunkd.log after trying to create the input:

```10-11-2017 21:57:51.431 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" Error getting password from encrypted store :null
10-11-2017 21:57:51.467 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10-11-2017 21:57:51.467 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: Defaulting to no-operation (NOP) logger implementation
10-11-2017 21:57:51.467 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" Error executing modular input : Permission denied : java.net.SocketException: Permission denied
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at sun.nio.ch.Net.bind0(Native Method)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at sun.nio.ch.Net.bind(Net.java:433)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at sun.nio.ch.Net.bind(Net.java:425)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:264)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at org.eclipse.jetty.server.Server.doStart(Server.java:303)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at com.splunk.modinput.alexa.AlexaWebService.startWebServer(Unknown Source)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at com.splunk.modinput.alexa.AlexaWebService.doRun(Unknown Source)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at com.splunk.modinput.ModularInput.init(Unknown Source)
10-11-2017 21:57:51.616 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py"       at com.splunk.modinput.alexa.AlexaWebService.main(Unknown Source)```

Splunk is running as root as is required, and has access to all my cert files from the keystore step. Any idea what's going on here?

**Comment by damiendallimore** [comment]
You’ll only get :


Error executing modular input : Permission denied : java.net.SocketException: Permission denied


If you cant open port 443 for HTTPS (that is what the Alexa App is trying to do in the stack trace)

Reasons : 

1) the port is already in use
2) you don’t have permission (but you mentioned you are running as root , so this should be fine)

**Comment by sodle** [comment]
Nothing is bound to 443 (`nmap localhost` doesn't show anything bound to it, anyway). Splunk appears to be running as root, and SELinux seems to be disabled. I'm on Amazon Linux.

**Comment by Bilelch** [comment]
I have the same issue here:

```
07-13-2018 15:09:40.910 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" Error getting password from encrypted store :null
07-13-2018 15:09:40.936 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
07-13-2018 15:09:40.936 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: Defaulting to no-operation (NOP) logger implementation
07-13-2018 15:09:40.936 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
for some reason java keystore cannot be loaded and I don't think its permission issue!!

**Comment by schofieldk** [comment]
I am also getting the same issue here - has anyone figured this out?

11-04-2018 21:30:33.023 +0000 INFO  ExecProcessor - New scheduled exec process: python /opt/splunk/etc/apps/splunk_monitoring_console/bin/dmc_config.py
11-04-2018 21:30:33.023 +0000 INFO  ExecProcessor - 	interval: run once
11-04-2018 21:30:33.806 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" Error getting password from encrypted store :null
11-04-2018 21:30:33.857 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
11-04-2018 21:30:33.857 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: Defaulting to no-operation (NOP) logger implementation
11-04-2018 21:30:33.857 +0000 ERROR ExecProcessor - message from "python /opt/splunk/etc/apps/alexa/bin/alexa.py" SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
